export { default as ImgArea } from './ImgArea'
export { default as MapArea } from './MapArea'
export { default as TabView } from './TabView'
export { default as ActionSheet } from './ActionSheet.tsx'
export { default as Swiper } from './Swiper'
export { default as RatingStars } from './RatingStars'
export { default as Avatar } from './Avatar'
