import { AdventureReview } from '~/core/data/adventure.data'

const reviews: AdventureReview[] = [
  {
    id: 1,
    contentId: 101,
    writer: { id: 1, username: 'user1', nickname: 'nickname1' },
    content: 'This is review content number 1. It is an exciting adventure!',
    score: 4,
  },
  {
    id: 2,
    contentId: 102,
    writer: { id: 2, username: 'user2', nickname: 'nickname2' },
    content: 'This is review content number 2. It is an exciting adventure!',
    score: 5,
  },
  {
    id: 3,
    contentId: 103,
    writer: { id: 3, username: 'user3', nickname: 'nickname3' },
    content: 'This is review content number 3. It is an exciting adventure!',
    score: 3,
  },
  {
    id: 4,
    contentId: 104,
    writer: { id: 4, username: 'user4', nickname: 'nickname4' },
    content: 'This is review content number 4. It is an exciting adventure!',
    score: 2,
  },
  {
    id: 5,
    contentId: 105,
    writer: { id: 5, username: 'user5', nickname: 'nickname5' },
    content: 'This is review content number 5. It is an exciting adventure!',
    score: 4,
  },
  {
    id: 6,
    contentId: 106,
    writer: { id: 6, username: 'user6', nickname: 'nickname6' },
    content: 'This is review content number 6. It is an exciting adventure!',
    score: 5,
  },
  {
    id: 7,
    contentId: 107,
    writer: { id: 7, username: 'user7', nickname: 'nickname7' },
    content: 'This is review content number 7. It is an exciting adventure!',
    score: 1,
  },
  {
    id: 8,
    contentId: 108,
    writer: { id: 8, username: 'user8', nickname: 'nickname8' },
    content: 'This is review content number 8. It is an exciting adventure!',
    score: 3,
  },
  {
    id: 9,
    contentId: 109,
    writer: { id: 9, username: 'user9', nickname: 'nickname9' },
    content: 'This is review content number 9. It is an exciting adventure!',
    score: 2,
  },
  {
    id: 10,
    contentId: 110,
    writer: { id: 10, username: 'user10', nickname: 'nickname10' },
    content: 'This is review content number 10. It is an exciting adventure!',
    score: 4,
  },
  {
    id: 11,
    contentId: 111,
    writer: { id: 11, username: 'user11', nickname: 'nickname11' },
    content: 'This is review content number 11. It is an exciting adventure!',
    score: 5,
  },
  {
    id: 12,
    contentId: 112,
    writer: { id: 12, username: 'user12', nickname: 'nickname12' },
    content: 'This is review content number 12. It is an exciting adventure!',
    score: 3,
  },
  {
    id: 13,
    contentId: 113,
    writer: { id: 13, username: 'user13', nickname: 'nickname13' },
    content: 'This is review content number 13. It is an exciting adventure!',
    score: 2,
  },
  {
    id: 14,
    contentId: 114,
    writer: { id: 14, username: 'user14', nickname: 'nickname14' },
    content: 'This is review content number 14. It is an exciting adventure!',
    score: 4,
  },
  {
    id: 15,
    contentId: 115,
    writer: { id: 15, username: 'user15', nickname: 'nickname15' },
    content: 'This is review content number 15. It is an exciting adventure!',
    score: 5,
  },
  {
    id: 16,
    contentId: 116,
    writer: { id: 16, username: 'user16', nickname: 'nickname16' },
    content: 'This is review content number 16. It is an exciting adventure!',
    score: 1,
  },
  {
    id: 17,
    contentId: 117,
    writer: { id: 17, username: 'user17', nickname: 'nickname17' },
    content: 'This is review content number 17. It is an exciting adventure!',
    score: 3,
  },
  {
    id: 18,
    contentId: 118,
    writer: { id: 18, username: 'user18', nickname: 'nickname18' },
    content: 'This is review content number 18. It is an exciting adventure!',
    score: 2,
  },
  {
    id: 19,
    contentId: 119,
    writer: { id: 19, username: 'user19', nickname: 'nickname19' },
    content: 'This is review content number 19. It is an exciting adventure!',
    score: 4,
  },
  {
    id: 20,
    contentId: 120,
    writer: { id: 20, username: 'user20', nickname: 'nickname20' },
    content: 'This is review content number 20. It is an exciting adventure!',
    score: 5,
  },
]

export { reviews }
