import { ActivityListData } from '~/core/dto/activity/activity.data'

const activities: ActivityListData[] = [
  {
    id: 1,
    activityType: 'MOUNTINE_CYCLING',
    user: { id: 1, username: 'user5', nickname: 'nick3' },
    title: 'Activity 1 Title',
    route: {
      activityType: 'CYCLING',
      id: 2,
      imgs: ['image_2_1.jpg', 'image_2_2.jpg'],
      name: 'Adventure3',
      rating: 4.7,
      difficulty: 'Hard',
      distance: 7.17,
      address: 'Address5',
    },
    distance: 17.49,
    elevationGain: 211.87,
    totalTime: 140,
    movingTime: 47,
    calories: 1295,
    splits: [
      { splitDistance: 4.76, elevationGain: 25.5, time: 54 },
      { splitDistance: 4.35, elevationGain: 28.3, time: 9 },
    ],
    rating: 2.9,
    description: 'This is a description for activity 1.',
    country: 'South Korea',
    city: 'Seoul',
    district: 'Mapo-gu',
    imgs: ['activity_1_1.jpg', 'activity_1_2.jpg'],
    createdAt: '2023-12-10 03:17:11',
  },
  {
    id: 2,
    activityType: 'HIKING',
    user: { id: 3, username: 'user5', nickname: 'nick5' },
    title: 'Activity 2 Title',
    route: {
      activityType: 'HIKING',
      id: 3,
      imgs: ['image_3_1.jpg', 'image_3_2.jpg'],
      name: 'Adventure5',
      rating: 2.5,
      difficulty: 'Hard',
      distance: 2.18,
      address: 'Address1',
    },
    distance: 2.38,
    elevationGain: 157.14,
    totalTime: 36,
    movingTime: 225,
    calories: 1263,
    splits: [
      { splitDistance: 4.19, elevationGain: 14.0, time: 30 },
      { splitDistance: 4.02, elevationGain: 30.9, time: 34 },
      { splitDistance: 3.03, elevationGain: 14.3, time: 20 },
      { splitDistance: 1.36, elevationGain: 76.3, time: 55 },
      { splitDistance: 3.28, elevationGain: 77.4, time: 16 },
    ],
    rating: 1.0,
    description: 'This is a description for activity 2.',
    country: 'South Korea',
    city: 'Seoul',
    district: 'Mapo-gu',
    imgs: ['activity_2_1.jpg', 'activity_2_2.jpg'],
    createdAt: '2022-07-22 00:30:59',
  },
  {
    id: 3,
    activityType: 'MOUNTINE_CYCLING',
    user: { id: 2, username: 'user5', nickname: 'nick1' },
    title: 'Activity 3 Title',
    route: {
      activityType: 'CYCLING',
      id: 3,
      imgs: ['image_3_1.jpg', 'image_3_2.jpg'],
      name: 'Adventure4',
      rating: 4.1,
      difficulty: 'Easy',
      distance: 13.74,
      address: 'Address3',
    },
    distance: 48.22,
    elevationGain: 91.67,
    totalTime: 112,
    movingTime: 246,
    calories: 1179,
    splits: [
      { splitDistance: 1.4, elevationGain: 92.7, time: 15 },
      { splitDistance: 3.23, elevationGain: 57.0, time: 36 },
      { splitDistance: 3.45, elevationGain: 82.5, time: 21 },
    ],
    rating: 3.3,
    description: 'This is a description for activity 3.',
    country: 'South Korea',
    city: 'Seoul',
    district: 'Mapo-gu',
    imgs: ['activity_3_1.jpg', 'activity_3_2.jpg'],
    createdAt: '2023-09-09 11:33:57',
  },
  {
    id: 4,
    activityType: 'HIKING',
    user: { id: 2, username: 'user2', nickname: 'nick2' },
    title: 'Activity 4 Title',
    route: {
      activityType: 'MOUNTINE_CYCLING',
      id: 4,
      imgs: ['image_4_1.jpg', 'image_4_2.jpg'],
      name: 'Adventure4',
      rating: 1.5,
      difficulty: 'Medium',
      distance: 3.98,
      address: 'Address2',
    },
    distance: 19.78,
    elevationGain: 364.68,
    totalTime: 35,
    movingTime: 246,
    calories: 1470,
    splits: [
      { splitDistance: 3.18, elevationGain: 31.6, time: 17 },
      { splitDistance: 1.68, elevationGain: 92.1, time: 35 },
    ],
    rating: 2.3,
    description: 'This is a description for activity 4.',
    country: 'South Korea',
    city: 'Seoul',
    district: 'Mapo-gu',
    imgs: ['activity_4_1.jpg', 'activity_4_2.jpg'],
    createdAt: '2023-06-18 08:13:53',
  },
  {
    id: 5,
    activityType: 'HIKING',
    user: { id: 5, username: 'user2', nickname: 'nick1' },
    title: 'Activity 5 Title',
    route: {
      activityType: 'HIKING',
      id: 1,
      imgs: ['image_1_1.jpg', 'image_1_2.jpg'],
      name: 'Adventure2',
      rating: 1.6,
      difficulty: 'Medium',
      distance: 16.68,
      address: 'Address2',
    },
    distance: 17.26,
    elevationGain: 265.52,
    totalTime: 208,
    movingTime: 82,
    calories: 505,
    splits: [
      { splitDistance: 4.09, elevationGain: 77.1, time: 21 },
      { splitDistance: 3.19, elevationGain: 83.8, time: 26 },
    ],
    rating: 2.8,
    description: 'This is a description for activity 5.',
    country: 'South Korea',
    city: 'Seoul',
    district: 'Mapo-gu',
    imgs: ['activity_5_1.jpg', 'activity_5_2.jpg'],
    createdAt: '2023-06-05 02:56:35',
  },
]

export { activities }
